### ISSUE TITLE
Weird vue router warnings on cold start

### ISSUE THREAD

**Issue by daniandl** [vuetifyjs/nuxt-module#150]
Thanks for trying to tackle all these Nuxt<>Vuetify issues with this library.

I pretty much copied the playground setup with the configFile variant, because I want to customize the components.
It works fine, the hydration time and cold start time is a bit longer, but that's normal, as Vuetify docs said.

However, the server and client logs print this:
```log
ℹ Vite server warmed up in 1447ms                                             4:21:32 PM
ℹ Vite client warmed up in 1668ms                                             4:21:32 PM
✔ Nitro built in 352 ms                                                 nitro 4:21:32 PM
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VAppBar/VAppBar.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VAppBar/VAppBar.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VAppBar/VAppBar.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VAppBar/VAppBar.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VImg/VImg.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VImg/VImg.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VImg/VImg.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VImg/VImg.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VApp/VApp.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VApp/VApp.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VApp/VApp.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VApp/VApp.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VToolbar/VToolbar.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VToolbar/VToolbar.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VToolbar/VToolbar.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VToolbar/VToolbar.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VBtn/VBtn.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VBtn/VBtn.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VBtn/VBtn.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VBtn/VBtn.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VBtnGroup/VBtnGroup.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VBtnGroup/VBtnGroup.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VBtnGroup/VBtnGroup.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VBtnGroup/VBtnGroup.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VIcon/VIcon.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VIcon/VIcon.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VIcon/VIcon.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VIcon/VIcon.sass"
[Vue Router warn]: No match found for location with path "/_nuxt/@plugin-vuetify/lib/components/VResponsive/VResponsive.sass"
... many more components :)
```

Just thought I'd document it, it's not really causing any issues (as far as I can tell).
Almost seems its the same issue we had to patch in the nitro response, except now its in vue router...

**Comment by userquin** [comment]
@daniandl we're checking what's the change in Nuxt, it is working properly in 3.8.0

**Comment by userquin** [comment]
@daniandl I'm going to release a new minor (breaking) updating to latest Nuxt (3.8.1), Vite (4.5.0) and Vuetify (3.4), it seems there are some internal breaking changes in Nuxt (I guess it is about types), tests on my local works without any sass router warnings/errors (dev tools still with `/@vite/client` warnings/errors)

**Comment by TouchSek** [comment]
Same issue.

**Comment by userquin** [comment]
The next minor will not solve the error (linked PR): https://github.com/nuxt/cli/issues/188

**Comment by hermes85pl** [comment]
For me, when using Node v20.15.0, with this module in version 0.15.2 the issue is not present, and I do experience it after switching to 0.16.1 (having all the other dependencies in the latest version).

**Comment by userquin** [comment]
can you try using latest 0.18.2 replacing `sass` with `sass-embedded` (1.77.8): it would be better to update also to latest Nuxt 3.13.* and Vite 5.4.3 (maybe you need to use `resolutions` or `overrides` in your packagejson) that solves a lot of sass issues: the issue is about the sass resolver.

**Comment by hermes85pl** [comment]
When I do, I get other error instead, upon loading a page from the dev server (anonymized):

```
[8:15:20 PM]  ERROR  Internal server error: [sass] Error: ENOENT: no such file or directory, open '/.../node_modules/.pnpm/vuetify@3.7.1_vite-plugin-vuetify@2.0.4_vue@3.5.3/node_modules/vuetify/lib/styles/main.sass?direct'
  ╷
2 │ @use "file:///.../node_modules/.pnpm/vuetify@3.7.1_vite-plugin-vuetify@2.0.4_vue@3.5.3/node_modules/vuetify/lib/styles/main.sass%3Fdirect"
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  file:///@vuetify-styles/lib/styles/main.sass 2:1  root stylesheet
  Plugin: vite:css
  File: /@vuetify-styles/lib/styles/main.sass:2:1
  Error: Error: ENOENT: no such file or directory, open '/.../node_modules/.pnpm/vuetify@3.7.1_vite-plugin-vuetify@2.0.4_vue@3.5.3/node_modules/vuetify/lib/styles/main.sass?direct'
    ╷
  2 │ @use "file:///.../node_modules/.pnpm/vuetify@3.7.1_vite-plugin-vuetify@2.0.4_vue@3.5.3/node_modules/vuetify/lib/styles/main.sass%3Fdirect"
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    file:///@vuetify-styles/lib/styles/main.sass 2:1  root stylesheet
      at handleCompileResponse (/.../node_modules/.pnpm/sass-embedded@1.78.0/node_modules/sass-embedded/lib/src/compiler/utils.ts:221:11)
      at AsyncCompiler.compileRequestAsync (/.../node_modules/.pnpm/sass-embedded@1.78.0/node_modules/sass-embedded/lib/src/compiler/async.ts:136:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at compileStringAsync (/.../node_modules/.pnpm/sass-embedded@1.78.0/node_modules/sass-embedded/lib/src/compile.ts:54:12)


 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/@vuetify-styles/lib/styles/main.sass"
```

**Comment by userquin** [comment]
Try removing the `node_modules/.vite` folder beware it is `.vite` not `vite` or run `pnpm dedupe`.

**Comment by userquin** [comment]
@daniandl is you repo public? If not, can you provide the nuxt config file?

**Comment by theAvocadoCoder** [comment]
I've also encountered this issue, using Nuxt 3.13.1 and vuetify-nuxt-module 0.18.2 ( and Node 20.15.1)

I got a lot of Vue Router warnings for all the Vuetify components I use in the app and ENOENT errors for the components' Sass files. Setting nuxt to 3.10.0 and vuetify-nuxt-module to 0.15.2 got rid of the server log errors as far as I can tell but there are still errors in my console when I open dev tools on my browser. 

I'm open to troubleshooting this so I've made a branch in my project with the modules set to their latest versions. I've tried replacing sass with sass-embedded and also used overrides to set vite to 5.4.3. That didn't change the errors I was getting. I should note that I'm very new to Nuxt and have not worked extensively with Sass either.

I've made [my repo](https://github.com/theAvocadoCoder/daily-bingo/tree/vnm-troubleshoot) public.

**Comment by userquin** [comment]
@theAvocadoCoder I'm going to do some changes: 
- write sass files to temporary file, will solve all the problems
- update logic to always configure the modern SASS compiler: right now using Vite defaults when Vite >= 5.4.2

I'll test your repo with pkg-pr-new from the new PR I'm preparing, I hope having 0v.18.3 release once tested.

NOTE: I cannot use `npm` in your repo, getting weird error about rollup binary, I'm testing it with `pnpm` on my local.

**Comment by theAvocadoCoder** [comment]
I'm not sure why the npm error happened, I use npm on my local. I've tested and this works. No errors or warnings related to the module in my browser console or the server logs and the styles are loading as they should. Thanks!

**Comment by userquin** [comment]
@theAvocadoCoder thx, releasing `v0.18.3`, I'll ping you here when released

**Comment by userquin** [comment]
@theAvocadoCoder `v0.18.3` released, change the vuetify-nuxt-module to `^0.18.3` and install dependencies, should be fixed

**Comment by theAvocadoCoder** [comment]
Yup! It is. Thankss

**Comment by TechAkayy** [comment]
Just a note, I was able to avoid the npm error by adding the package throwing error as an optionalDependencies in my package.json, something to do with [npm](https://github.com/npm/cli/issues/4828#issuecomment-2328919455) itself. 

```
  "optionalDependencies": {
    "@rollup/rollup-darwin-arm64": "*"
  }
```

**Comment by daniandl** [comment]
I can't reproduce this anymore with 0.18.3, Vite 5.4.10 and:

```
- Operating System: `Darwin`
- Node Version:     `v20.17.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.15.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.9.0`
```

So I will close this for now :)
