### ISSUE TITLE
Question: How to access appConfig in configfile

### ISSUE THREAD

**Issue by derHodrig** [vuetifyjs/nuxt-module#285]
I have setup the app like this: https://vuetify-nuxt-module.netlify.app/guide/vuetify-configuration-file.html

My app.config got an object theme with theme.actTheme = ThemeAbc.name

I wonder, if its possible to access the app.config inside the vuetify config file, so I can setup the vuetify themes there: 

```ts
theme: {
    defaultTheme: appConfig.theme.actTheme,
    themes: {
      ThemeAbc,
      ...
    },
  },
```

for this I have to call the useAppConfig() composable. Is this possible, if yes how? I could not get it to work.

**Comment by userquin** [comment]
I guess you can use `useAppConfig` in a new plugin hook: https://vuetify-nuxt-module.netlify.app/guide/nuxt-runtime-hooks.html (use `vuetify:before-create` hook, the options passed will be used to call `createVuetify`, juts add your themes inside the hook)

**Comment by derHodrig** [comment]
Thank you for your fast response.

I will close the issue, because i will not going further with nuxt.
